In [1]:
import pandas as pd
import pyodbc

print("Pandas version:", pd.__version__)
print("pyodbc imported successfully")

Pandas version: 3.0.5
pyodbc imported successfully

In [2]:
import pyodbc

print(pyodbc.drivers())

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [4]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={SQL Server};"
    r"SERVER=Z14-55N\SQLEXPRESS;"
    "DATABASE=master;"
    "Trusted_Connection=yes;"
)

print("SQL Server connected successfully!")

SQL Server connected successfully!

In [7]:
conn.autocommit = True

cursor = conn.cursor()

cursor.execute("""
IF DB_ID('MLDatabase') IS NULL
BEGIN
    CREATE DATABASE MLDatabase
END
""")

print("MLDatabase created successfully!")

MLDatabase created successfully!

In [8]:
cursor.execute("""
SELECT name
FROM sys.databases
WHERE name = 'MLDatabase'
""")

for row in cursor:
    print(row[0])

MLDatabase

In [9]:
conn.close()

conn = pyodbc.connect(
    "DRIVER={SQL Server};"
    r"SERVER=Z14-55N\SQLEXPRESS;"
    "DATABASE=MLDatabase;"
    "Trusted_Connection=yes;"
)

print("Connected to MLDatabase successfully!")

Connected to MLDatabase successfully!

In [10]:
cursor = conn.cursor()

cursor.execute("""
IF OBJECT_ID('Customers', 'U') IS NULL
BEGIN
    CREATE TABLE Customers (
        CustomerID INT,
        Age INT,
        Income FLOAT,
        PurchaseAmount FLOAT
    )
END
""")

conn.commit()

print("Customers table created successfully!")

Customers table created successfully!

In [11]:
cursor.execute("DELETE FROM Customers")

data = [
    (1, 22, 25000, 1200),
    (2, 28, 35000, 1800),
    (3, 35, 50000, 2500),
    (4, 42, 65000, 3200),
    (5, 30, 45000, 2100)
]

cursor.executemany("""
INSERT INTO Customers
(CustomerID, Age, Income, PurchaseAmount)
VALUES (?, ?, ?, ?)
""", data)

conn.commit()

print("Sample data inserted successfully!")

Sample data inserted successfully!

In [12]:
query = "SELECT * FROM Customers"

df = pd.read_sql(query, conn)

df

C:\Users\acer\AppData\Local\Temp\ipykernel_17580\1544698197.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   CustomerID  Age   Income  PurchaseAmount
0           1   22  25000.0          1200.0
1           2   28  35000.0          1800.0
2           3   35  50000.0          2500.0
3           4   42  65000.0          3200.0
4           5   30  45000.0          2100.0

In [13]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
display(df.head())

Shape: (5, 4)

Columns:
['CustomerID', 'Age', 'Income', 'PurchaseAmount']

Data types:
CustomerID          int64
Age                 int64
Income            float64
PurchaseAmount    float64
dtype: object

First 5 rows:

   CustomerID  Age   Income  PurchaseAmount
0           1   22  25000.0          1200.0
1           2   28  35000.0          1800.0
2           3   35  50000.0          2500.0
3           4   42  65000.0          3200.0
4           5   30  45000.0          2100.0